### ISSUE TITLE
Display version of CWL/WDL/etc supported

### ISSUE THREAD

**Issue by kinow** [PMCC-BioinformaticsCore/janis#56]
I was re-reading the CWL docs, catching up on new things since I last read the guide like the conditional steps. I went to see if Janis was already supporting CWL 1.2, and found this open issue https://github.com/PMCC-BioinformaticsCore/janis/issues/9

Other parts of the doc quote the 1.1 spec

![image](https://user-images.githubusercontent.com/304786/130702411-4d2b85ea-b126-4564-9e56-4904081cb09d.png)

I couldn't find anywhere clearly saying whether the CWL version supported in Janis is the 1.0, 1.1, 1.2, etc. Is it listed anywhere? I think it would be useful for users if this appeared somewhere in the README and/or project landing page (or in the CWL docs section).

**Comment by kinow** [comment]
I think the translated workflow will be using/declaring 1.2, so maybe that's the supported version at the moment? https://github.com/PMCC-BioinformaticsCore/janis-core/blob/0b5b79fee09d3fcd6bf78bd7c883474eef1f3e9c/janis_core/translations/cwl.py#L72

**Comment by illusional** [comment]
Hey Bruno, thanks for the feedback! You're right, we're generating:

- CWL `v1.2` (as it's the minimum version that supports conditionals, and >=v1.1 supports ToolTimeLimit)
- WDL `development` (Cromwell team codenames this _Biscayne_), as it supports the Directory type and the `sep` function. I'm watching the [WDL v1.2 discussion here](https://github.com/openwdl/wdl/discussions/473) as we should theoretically support that if it gets proposed (rather than 2.0). We've removed interpolation blocks and replaced with functions from the standard library to prepare for future changes though, and it's easier to translate.

I've created #57 to address your feedback.

**Comment by kinow** [comment]
Thanks @illusional ! 

I added another post-it for later about JavaScript & CWL. Is that supported in Janis too? Couldn't find it in the FAQ. Now I'm looking for some docs on limitations, but so far only found this one https://janis.readthedocs.io/en/latest/references/engines.html#limitations
